# Generated by Django 4.2.23 on 2025-08-26 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="评分")),
                (
                    "verified_purchase",
                    models.CharField(max_length=1, verbose_name="是否验证购买"),
                ),
                (
                    "product_category",
                    models.CharField(max_length=50, verbose_name="产品类别"),
                ),
                (
                    "product_title",
                    models.CharField(max_length=200, verbose_name="产品标题"),
                ),
                (
                    "review_title",
                    models.CharField(max_length=200, verbose_name="评论标题"),
                ),
                ("review_text", models.TextField(verbose_name="评论内容")),
                (
                    "prediction_result",
                    models.CharField(
                        choices=[("REAL", "真实评论"), ("FAKE", "虚假评论")],
                        max_length=4,
                        verbose_name="预测结果",
                    ),
                ),
                ("fake_probability", models.FloatField(verbose_name="虚假概率")),
                ("real_probability", models.FloatField(verbose_name="真实概率")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "分析失败"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论分析记录",
                "verbose_name_plural": "评论分析记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
